FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

ENV DEBIAN_FRONTEND noninteractive\
    SHELL=/bin/bash
RUN apt-get update && apt-get install -y --no-install-recommends wget
WORKDIR /app
RUN pip install deepface fastapi uvicorn && pip uninstall opencv-python -y && pip install opencv-python-headless 
RUN pip install awslambdaric mangum
COPY serve.py  haarcascade_frontalface_default.xml download_model.py .
ENV HOME=/app
RUN python download_model.py

ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD [ "serve.handler" ] 